### PR TITLE
Add subjectAltNames to all server certificates

### LINKED ISSUE #4: Adding subjectAltNames to certificates
Most of the badtls.io test certificates contain only a common name and no subjectAltNames. Support for such certificates is deprecated, in the process of being deprecated or not implemented to begin with in some libraries and applications. For reference:
- urllib3: https://github.com/shazow/urllib3/issues/497
- Chromium: https://bugs.chromium.org/p/chromium/issues/detail?id=308330
- Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1088998
- webpki: https://github.com/briansmith/webpki/issues/11

It might be a good idea to add subjectAltNames to badtls.io certificates. That would allow testing a wider variety of subjects, and maybe even avoid false passes (such as not rejecting expired.badtls.io:11006 because of expiration, but because of missing subjectAltNames).

### PR DESCRIPTION
**Pull request by jviide**
Modify `scripts/cert_*.py` scripts to add subjectAltNames to all _server_ certificates for reasons outlined in issue #4. The common names remain as they were. Feel free to just close this pull request if the changes are outside the scope of badtls.io :)

As a side note, this does make domain-match and san-match tests quite similar, except that the san-match doesn't have a domain name as its common name.

Closes #4.

### CODE REVIEW

**Comment by wbond** [comment]
We should probably include a test now that includes just a common name with no SAN, allowing projects to use it if they wish, for backwards compat.

**Comment by jviide** [comment]
Roger that. What do you think, should it be a new test? Or should I just revert the changes to some existing one, such as domain-match?

**Comment by wbond** [comment]
Let's set up `no-san.badtls.io:10006`. I just added DNS for it, which should appear shortly.

The existing tests should be good since they test the combination of a cert with a `common_name` and SAN with the same domain, and then a generic `common_name` and a SAN.

Thanks again for your time in contributing!

**Comment by jviide** [comment]
Oo, nice! Should I add the no-san test as a part of this pull request, or do you want to handle it separately?

**Comment by wbond** [comment]
Let's do it as part of this change

**Comment by jviide** [comment]
Added no-san generation script, cert & config, imitating the corresponding parts of the domain-match test.

**Comment by wbond** [comment]
I think the only remaining part is to add the actual regenerated certs to the PR for each of the scripts that was changed.

**Comment by jviide** [comment]
Good point. I regenerated bad-key-usage, domain-match, expired-1963, expired, future, weak-sig and wildcard certs.

**Comment by wbond** [comment]
These should all be live now

**Comment by wbond** [comment]
Thanks for the changes and the info!

**Comment by jviide** [comment]
🎉 Thanks!

**Pull request merged**
