### PR TITLE
Add Dockerfile

### PR DESCRIPTION
**Pull request by joneskoo**
Running badtls.io with Docker makes it quick to replicate the stack.

### CODE REVIEW

**Comment by wbond** [comment]
Could you add a small section to the readme about docker being supported and an example command in how to launch it? I would imagine it would be most useful targeted at users who are beginners when it comes to Docker.

**Comment by joneskoo** [comment]
Sure, I thought about that but wanted to check if you want a Dockerfile in
the first place. :)

To make it even easier you could publish this in docker hub but it's
trivial to build so no big deal. Less things to update.

The commands to use are as comments in Dockerfile but some context is
needed for readme. I'll do that when I get a chance.

SNI would make it shorter with less ports to map. Any thoughts why no SNI
default vhost?

**Comment by wbond** [comment]
The reason I don't use SNI is because this was built (instead of using badssl.com) to allow testing oscrypto on Windows XP, and SChannel on XP does not support SNI.

**Comment by joneskoo** [comment]
Ok so it would make sense to add the SNI default vhost but have the
examples continue to support port based model. Makes sense.

Thanks

**Pull request closed without merging**
